In [1]:
import yfinance as yf
import pandas as pd
import datetime

import sys
# Add 'data-loader' directory to the Python path
sys.path.append('data-loader') 

from utils import *

EXCHANGE_ID = "979f24c6-0c23-4158-aaa8-770febb76d9a"
ASSET_ID = "276a8657-e718-4bef-a997-dd8daee9fcc4"

base_url = "http://0.0.0.0:5000/"

In [2]:
final_timestamp = int(datetime.now().timestamp())


# Get the asset from the API
asset = api_request_get_asset_from_asset_id(base_url,EXCHANGE_ID,ASSET_ID)

# Get the last recorded price timestamp for the specified asset ID
last_timestamp , first_report  = get_last_timestamp(base_url,ASSET_ID,asset["interval"].iloc[0])

# Get the prices from the BINANCE API
df_prices_final = get_data_from_api(symbol=asset["symbol"].iloc[0], interval=asset["interval"].iloc[0], initial_timestamp=last_timestamp, limit_timestamp=final_timestamp)

# Upload the prices to the API
upload_prices(df_prices_final,base_url,ASSET_ID)

df_with_indicators = get_full_prices_past( base_url, ASSET_ID, asset["interval"].iloc[0], last_timestamp, first_report,final_timestamp)


df_extra_assets_data = create_df_extra_assets_data(start_date=last_timestamp, end_date=final_timestamp)

df_final = pd.merge(df_with_indicators, df_extra_assets_data , on='timestamp_round_day', how='outer')

# upload_indicators(df_final,base_url,ASSET_ID)

get asset status code: 200
symbol: BTCUSDT
interval: day
entro api_request_last_time_stamp_from_asset_id
get las unix time status code: 200
last time in the api: 2023-04-07 00:00:00
Actual datetime: 2023-04-08 00:00:00
Finalizo y no hay datos
There are NO prices to upload
DONE upload_prices
entro api_request_get_prices_between_unix_time
unix_time_start: 1672185600
unix_time_end: 1680940745
asset_id: 276a8657-e718-4bef-a997-dd8daee9fcc4
status code time between: 200
get prices between status code: 200
Getting data for: gold GC=F

/Users/julianoliverosforero/Desktop/2023-1/Tesis/cryptocurrency-market-prediction-project/data-loader/env/lib/python3.9/site-packages/ta/trend.py:780: RuntimeWarning: invalid value encountered in scalar divide
  dip[idx] = 100 * (self._dip[idx] / value)
/Users/julianoliverosforero/Desktop/2023-1/Tesis/cryptocurrency-market-prediction-project/data-loader/env/lib/python3.9/site-packages/ta/trend.py:785: RuntimeWarning: invalid value encountered in scalar divide
  din[idx] = 100 * (self._din[idx] / value)
/Users/julianoliverosforero/Desktop/2023-1/Tesis/cryptocurrency-market-prediction-project/data-loader/utils.py:547: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_prices_wit_indicators['timestamp_round_day'] = df_prices_wit_indicators['unix_time'].apply(round_day)

DONE getting data forgold GC=F
Getting data for: silver  SI=F
DONE getting data forsilver  SI=F

In [3]:
df_with_indicators

,unix_time,id,ao,kama,ppo,pvo,roc,rsi,stochrsi,stoch,...,mi,sma,wma,stc,trix,psar_down_indicator,psar_up_indicator,vi_pos,vi_neg,timestamp_round_day
99,1680739200,b6dce153-d216-43ad-89f7-492d38554f33,2354.457824,27121.206071,3.482874,-47.438388,2.078691,59.462436,0.125541,57.001950,...,25.825025,27999.201667,28135.439111,6.249997,0.646968,0.0,0.0,1.043175,1.040464,1680739200
100,1680825600,42c91b1a-ecce-4ff1-89dd-6095371a1197,2136.334412,27148.990680,3.224732,-50.138660,-0.220680,58.251851,0.000000,52.238711,...,25.157167,27994.058333,28080.340889,3.124999,0.619561,0.0,0.0,1.059019,1.021108,1680825600

In [4]:
df_extra_assets_data

          gold  unix_time_x  timestamp_round_day    silver   unix_time_y
0  2023.699951   1680739200           1680739200  25.129999   1680739200

In [5]:
df_final

,unix_time,id,ao,kama,ppo,pvo,roc,rsi,stochrsi,stoch,...,trix,psar_down_indicator,psar_up_indicator,vi_pos,vi_neg,timestamp_round_day,gold,unix_time_x,silver,unix_time_y
0,1680739200,b6dce153-d216-43ad-89f7-492d38554f33,2354.457824,27121.206071,3.482874,-47.438388,2.078691,59.462436,0.125541,57.001950,...,0.646968,0.0,0.0,1.043175,1.040464,1680739200,2023.699951,1.680739e+09,25.129999,1.680739e+09
1,1680825600,42c91b1a-ecce-4ff1-89dd-6095371a1197,2136.334412,27148.990680,3.224732,-50.138660,-0.220680,58.251851,0.000000,52.238711,...,0.619561,0.0,0.0,1.059019,1.021108,1680825600,NaN,NaN,NaN,NaN